name: Test Secrets

on:
  workflow_dispatch:

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print if secret exists
        run: |
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "❌ Secret is missing"
            exit 1
          else
            echo "✅ Secret is available (not printing for security)"
          fi
