name: Test Secret Value

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check if DISCORD_WEBHOOK is set
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ -z "$DISCORD_WEBHOOK" ]; then
            echo "❌ DISCORD_WEBHOOK is missing"
            exit 1
          else
            echo "✅ DISCORD_WEBHOOK is available"
          fi
